version: '3.7'

services:

  postgresql:
    image: timescale/timescaledb:2.0.2-pg11
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    env_file:
      - env.postgresql
      - .env.postgresql
    ports:
      - 55432:5432
    networks: ['db']

networks:
  db:
    driver: bridge


volumes:
  postgresql_data:
    driver: local